In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [35]:
import sklearn.preprocessing

In [ ]:
a=X[:,1]
a=a.tolist()

In [66]:
label_binarizer = sklearn.preprocessing.LabelBinarizer()

In [ ]:
label_binarizer.fit(range(max(a)+1))

In [89]:
b = label_binarizer.transform(a)

In [121]:
X=np.concatenate((b,X),1)

In [129]:
X=X[:,1:]

In [130]:
X

array([[0, 0, 619, ..., 1, 1, 101348.88],
       [0, 1, 608, ..., 0, 1, 112542.58],
       [0, 0, 502, ..., 1, 0, 113931.57],
       ...,
       [0, 0, 709, ..., 0, 1, 42085.58],
       [1, 0, 772, ..., 1, 0, 92888.52],
       [0, 0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [131]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [134]:
print(X.shape,y.shape)

(10000, 11) (10000,)


In [135]:
from sklearn.model_selection import train_test_split

In [136]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [145]:
X_train.shape

(8000, 11)

In [144]:
X_test.shape

(2000, 11)

In [142]:
len(y_train)

8000

In [143]:
len(y_test)

2000

In [164]:
from sklearn.preprocessing import StandardScaler

In [167]:
scaler = StandardScaler()

In [175]:
X_test=scaler.fit_transform(X_test)
X_train=scaler.fit_transform(X_train)

In [180]:
X_test.shape

(2000, 11)

In [181]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [184]:
classifier=Sequential()

In [185]:
classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [186]:
classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [187]:
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid',))

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [190]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [191]:
classifier.fit(X_train,y_train,batch_size=10,nb_epoch=100)

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
8000/8000 [==============================] - 2s 215us/step - loss: 0.4959 - accuracy: 0.7951
Epoch 2/100
8000/8000 [==============================] - 1s 185us/step - loss: 0.4287 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.4235 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.4202 - accuracy: 0.8079
Epoch 5/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.4171 - accuracy: 0.8251
Epoch 6/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.4158 - accuracy: 0.8291
Epoch 7/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.4139 - accuracy: 0.8294
Epoch 8/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.4126 - accuracy: 0.8319
Epoch 9/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.4114 - accuracy: 0.8328
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 2s 194us/step - loss: 0.4006 - accuracy: 0.8357
Epoch 79/100
8000/8000 [==============================] - 2s 190us/step - loss: 0.4005 - accuracy: 0.8355
Epoch 80/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.4008 - accuracy: 0.8351
Epoch 81/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.4004 - accuracy: 0.8353
Epoch 82/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.4007 - accuracy: 0.8357
Epoch 83/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.4004 - accuracy: 0.8339
Epoch 84/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.4005 - accuracy: 0.8355
Epoch 85/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.4006 - accuracy: 0.8357
Epoch 86/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.4003 - accuracy: 0.8347
Epoch 87/100
8000/8000 [==============================] - 1

In [192]:
y_pred=classifier.predict(X_test)

In [197]:
y_pred_tf=(y_pred>0.5)

In [208]:
y_pred_tf[5]

array([ True])

In [215]:
if(y_test[6]==y_pred_tf[5]):
    print('cool')

In [217]:
cnt_true=0
cnt_fls=0

In [220]:
for i in range(len(X_test)):
    if(y_test[i]==y_pred_tf[i]):
        cnt_true=cnt_true+1
    else:
        cnt_fls=cnt_fls+1

In [224]:
(cnt_true/2000)*100

84.2

In [226]:
cnt_true

1684

In [227]:
cnt_fls

316

In [228]:
from sklearn.metrics import confusion_matrix

In [231]:
cm=confusion_matrix(y_test,y_pred_tf)

In [232]:
cm

array([[1540,   55],
       [ 261,  144]], dtype=int64)

In [237]:
((1540+144)/2000)*100

84.2